image: python:3.6.1

services:
  - name: postgres
    alias: db

variables:
  POSTGRES_DB: acme
  POSTGRES_HOST: db
  POSTGRES_USER: acme
  POSTGRES_PASSWORD: "acme_saison2"

test:
    script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/acme
    - pip install -r requirements.txt
    - cd code
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test api/tests -v 2