version: '3.7'

services: 
    db : 
        image: postgres:12
        container_name: db
        environment: 
            POSTGRES_PASSWORD: 'postgres'
        volumes: 
            - drf_pg_volume:/var/lib/postgresql/data
        networks:
            - socle_proxypass_network
    adminer : 
        image: adminer:4.7.7
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on: 
            - db
        networks:
            - socle_proxypass_network
    web :
        container_name: web
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./code:/code
        ports:
           - 8000:8000
        depends_on:
            - db
        networks:
            - socle_proxypass_network

volumes:
    drf_pg_volume:

networks:
  socle_proxypass_network:
    external:
      name: proxypass_network

#coucou